# spring boot 2.6 이후 버전에 의해서 spring.mvc.pathmatch.matching-strategy 값이 
# ant_apth_matcher에서 path_pattern_parser로 변경되면서 몇몇 라이브러리에서 에러 발생
# -> 수동으로 값 변경
spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: commtalk
    password: Commtalk123!@#
    url: jdbc:mysql://127.0.0.1:3306/commtalk_db?allowPublicKeyRetrieval=true&useSSL=false
  jpa:
    show-sql: true
    open-in-view: true
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: false
  security:
    user:
      name: talktalk
      password: 1234

servlet:
  multipart:
    file-size-threshold: 1MB
    location: C:/commtalk_data/
    max-file-size: 100MB
    max-request-size: 100MB

jwt:
  secret: NF3Le1cZvVXk3ZRcvNX0C4G8fVRS0sTOeTk4m8fgz08dMnsA9Nzz2qQAVbuqzYxH
  expiration: 3600000
